"""increase password hash length

Revision ID: 03edfc62b5e4
Revises: fb21cf87fb7d
Create Date: 2025-04-14 14:54:13.427844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03edfc62b5e4'
down_revision = 'fb21cf87fb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
